import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:barzidorock_f/models/venue.dart';

List<Venue> getHongdaeVenues() {
  return [
    Venue(
      id: 'hongdae_ttok',
      name: '뚝 홍대',
      description: '홍대의 대표적인 인디 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.557012, 126.924678),
      rating: 4.7,
      category: '인디 공연장',
      ticketUrl: 'https://example.com/ticket1',
      address: '서울특별시 마포구 와우산로17길 19',
      phoneNumber: '02-323-5555',
    ),
    Venue(
      id: 'hongdae_skullhong',
      name: '스컬홍 라이브',
      description: '홍대의 유명한 록 음악 라이브 하우스',
      imageUrl: '',
      location: const LatLng(37.556789, 126.923945),
      rating: 4.8,
      category: '록 공연장',
      ticketUrl: 'https://example.com/ticket2',
      address: '서울특별시 마포구 서교동 354-7',
      phoneNumber: '02-334-6666',
    ),
    Venue(
      id: 'hongdae_hbf',
      name: 'HBF 홍대',
      description: '홍대의 헤비메탈 전문 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.557456, 126.925789),
      rating: 4.6,
      category: '메탈 공연장',
      ticketUrl: 'https://example.com/ticket3',
      address: '서울특별시 마포구 연남동 224-11',
      phoneNumber: '02-345-7777',
    ),
    Venue(
      id: 'hongdae_jukebox',
      name: 'Jukebox 홍대',
      description: '홍대의 클래식 라이브 바',
      imageUrl: '',
      location: const LatLng(37.555876, 126.922765),
      rating: 4.5,
      category: '라이브 바',
      ticketUrl: 'https://example.com/ticket4',
      address: '서울특별시 마포구 서교동 360-7',
      phoneNumber: '02-356-8888',
    ),
    Venue(
      id: 'hongdae_freebird',
      name: 'Freebird 홍대',
      description: '홍대의 록 음악 전문 라이브 하우스',
      imageUrl: '',
      location: const LatLng(37.555234, 126.921987),
      rating: 4.7,
      category: '록 공연장',
      ticketUrl: 'https://example.com/ticket5',
      address: '서울특별시 마포구 와우산로 108',
      phoneNumber: '02-367-9999',
    ),
    Venue(
      id: 'hongdae_gb10',
      name: 'GB10 홍대',
      description: '홍대의 오래된 인디 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.554987, 126.921543),
      rating: 4.6,
      category: '인디 공연장',
      ticketUrl: 'https://example.com/ticket6',
      address: '서울특별시 마포구 서교동 347-12',
      phoneNumber: '02-378-0000',
    ),
    Venue(
      id: 'hongdae_spotlive',
      name: 'Spot Live 홍대',
      description: '홍대의 새로운 라이브 음악 공연장',
      imageUrl: '',
      location: const LatLng(37.557890, 126.926876),
      rating: 4.4,
      category: '라이브 공연장',
      ticketUrl: 'https://example.com/ticket7',
      address: '서울특별시 마포구 연남동 223-15',
      phoneNumber: '02-389-1111',
    ),
    Venue(
      id: 'hongdae_evans',
      name: "Evans 홍대",
      description: '홍대의 재즈 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.559123, 126.928567),
      rating: 4.9,
      category: '재즈 클럽',
      ticketUrl: 'https://example.com/ticket8',
      address: '서울특별시 마포구 연남동 231-4',
      phoneNumber: '02-390-2222',
    ),
    Venue(
      id: 'hongdae_loststar',
      name: 'Lost Star 홍대',
      description: '홍대의 어쿠스틱 라이브 카페',
      imageUrl: '',
      location: const LatLng(37.554678, 126.921234),
      rating: 4.3,
      category: '라이브 카페',
      ticketUrl: 'https://example.com/ticket9',
      address: '서울특별시 마포구 서교동 339-8',
      phoneNumber: '02-401-3333',
    ),
    Venue(
      id: 'hongdae_nest',
      name: 'The Nest 홍대',
      description: '홍대의 언더그라운드 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.558123, 126.927456),
      rating: 4.5,
      category: '언더그라운드 공연장',
      ticketUrl: 'https://example.com/ticket10',
      address: '서울특별시 마포구 연남동 227-22',
      phoneNumber: '02-412-4444',
    ),
    Venue(
      id: 'hongdae_blujaz',
      name: 'Blu Jaz 홍대',
      description: '홍대의 펑키한 글로벌 바&그릴에서 라이브 공연을 즐기세요',
      imageUrl: '',
      location: const LatLng(37.557234, 126.924987),
      rating: 4.5,
      category: '라이브 공연장',
      ticketUrl: 'https://example.com/ticket11',
      address: '서울특별시 마포구 홍대길 27',
      phoneNumber: '02-423-5555',
    ),
    Venue(
      id: 'hongdae_therock',
      name: 'The Rock 홍대',
      description: '홍대의 클래식 록 라이브 바',
      imageUrl: '',
      location: const LatLng(37.556345, 126.923567),
      rating: 4.6,
      category: '라이브 바',
      ticketUrl: 'https://example.com/ticket12',
      address: '서울특별시 마포구 서교동 352-3',
      phoneNumber: '02-434-6666',
    ),
  ];
}

List<Venue> getItaewonVenues() {
  return [
    Venue(
      id: 'itaewon_hardrock',
      name: 'Hard Rock 이태원',
      description: '이태원의 유명한 록 라이브 하우스',
      imageUrl: '',
      location: const LatLng(37.535123, 126.984567),
      rating: 4.7,
      category: '록 공연장',
      ticketUrl: 'https://example.com/ticket13',
      address: '서울특별시 용산구 이태원로 172',
      phoneNumber: '02-799-8888',
    ),
    Venue(
      id: 'itaewon_theinn',
      name: 'The Inn Livehouse 이태원',
      description: '이태원에 위치한 인기 라이브 음악 바',
      imageUrl: '',
      location: const LatLng(37.535567, 126.985123),
      rating: 4.8,
      category: '라이브 음악 바',
      ticketUrl: 'https://example.com/ticket14',
      address: '서울특별시 용산구 이태원동 128-5',
      phoneNumber: '02-788-7777',
    ),
    Venue(
      id: 'itaewon_blujaz',
      name: 'Blu Jaz 이태원',
      description: '이태원의 펑키한 글로벌 바&그릴에서 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.534789, 126.983765),
      rating: 4.4,
      category: '술집',
      ticketUrl: 'https://example.com/ticket15',
      address: '서울특별시 용산구 이태원로 154',
      phoneNumber: '02-777-6666',
    ),
    Venue(
      id: 'itaewon_lenoir',
      name: 'Le Noir 이태원',
      description: '이태원의 분위기 좋은 칵테일 바에서 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.536098, 126.985789),
      rating: 4.6,
      category: '칵테일바',
      ticketUrl: 'https://example.com/ticket16',
      address: '서울특별시 용산구 이태원동 135-2',
      phoneNumber: '02-766-5555',
    ),
    Venue(
      id: 'itaewon_bluefire',
      name: 'Bluefire Beach Club 이태원',
      description: '이태원의 인기 술집에서 라이브 음악과 해변 분위기',
      imageUrl: '',
      location: const LatLng(37.533456, 126.982123),
      rating: 4.5,
      category: '술집',
      ticketUrl: 'https://example.com/ticket17',
      address: '서울특별시 용산구 회나무로 23',
      phoneNumber: '02-755-4444',
    ),
    Venue(
      id: 'itaewon_rockstar',
      name: 'Rock Star 이태원',
      description: '이태원의 록 라이브 하우스',
      imageUrl: '',
      location: const LatLng(37.536345, 126.986234),
      rating: 4.6,
      category: '록 공연장',
      ticketUrl: 'https://example.com/ticket18',
      address: '서울특별시 용산구 이태원동 142-7',
      phoneNumber: '02-744-3333',
    ),
    Venue(
      id: 'itaewon_bluenote',
      name: 'Blue Note 이태원',
      description: '이태원의 재즈 라이브 클럽',
      imageUrl: '',
      location: const LatLng(37.534098, 126.981345),
      rating: 4.8,
      category: '재즈 클럽',
      ticketUrl: 'https://example.com/ticket19',
      address: '서울특별시 용산구 이태원로 145',
      phoneNumber: '02-733-2222',
    ),
    Venue(
      id: 'itaewon_underground',
      name: 'Underground 이태원',
      description: '이태원의 언더그라운드 라이브 공연장',
      imageUrl: '',
      location: const LatLng(37.535789, 126.984345),
      rating: 4.4,
      category: '언더그라운드 공연장',
      ticketUrl: 'https://example.com/ticket20',
      address: '서울특별시 용산구 이태원동 131-9',
      phoneNumber: '02-722-1111',
    ),
    Venue(
      id: 'itaewon_woody',
      name: 'Woody Live 이태원',
      description: '이태원의 어쿠스틱 라이브 카페',
      imageUrl: '',
      location: const LatLng(37.533123, 126.981567),
      rating: 4.5,
      category: '라이브 카페',
      ticketUrl: 'https://example.com/ticket21',
      address: '서울특별시 용산구 회나무로 17',
      phoneNumber: '02-711-0000',
    ),
    Venue(
      id: 'itaewon_moonnight',
      name: 'Moon Night 이태원',
      description: '이태원의 분위기 좋은 라이브 바',
      imageUrl: '',
      location: const LatLng(37.536789, 126.986789),
      rating: 4.7,
      category: '라이브 바',
      ticketUrl: 'https://example.com/ticket22',
      address: '서울특별시 용산구 이태원동 150-3',
      phoneNumber: '02-700-9999',
    ),
  ];
}