import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:barzidorock_f/models/venue.dart';

List<Venue> getHongdaeVenues() {
  return [
    Venue(
      id: 'hongdae_livehouse_1',
      name: 'The Inn Livehouse @ 홍대',
      description: '홍대에 위치한 인기 라이브 음악 바',
      imageUrl: '',
      location: const LatLng(37.5570, 126.9260),
      rating: 4.8,
      category: '라이브 음악 바',
      ticketUrl: 'https://example.com/ticket1',
      address: '서울특별시 마포구 홍대입구역',
      phoneNumber: '02-1234-5678',
    ),
    Venue(
      id: 'hongdae_blujaz_1',
      name: 'Blu Jaz, 홍대점',
      description: '홍대의 펑키한 글로벌 바&그릴에서 라이브 공연을 즐기세요',
      imageUrl: '',
      location: const LatLng(37.5578, 126.9255),
      rating: 4.3,
      category: '라이브 공연장',
      ticketUrl: 'https://example.com/ticket2',
      address: '서울특별시 마포구 홍대',
      phoneNumber: '02-2345-6789',
    ),
    Venue(
      id: 'hongdae_lenoir_1',
      name: 'Le Noir @ 홍대',
      description: '홍대의 분위기 좋은 칵테일 바에서 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.5565, 126.9240),
      rating: 4.8,
      category: '칵테일바',
      ticketUrl: 'https://example.com/ticket3',
      address: '서울특별시 마포구 홍대',
      phoneNumber: '02-3456-7890',
    ),
    Venue(
      id: 'hongdae_bluefire_1',
      name: 'Bluefire Beach Club 홍대',
      description: '홍대의 인기 술집에서 라이브 음악과 해변 분위기',
      imageUrl: '',
      location: const LatLng(37.5580, 126.9270),
      rating: 4.7,
      category: '술집',
      ticketUrl: 'https://example.com/ticket4',
      address: '서울특별시 마포구 홍대입구',
      phoneNumber: '02-4567-8901',
    ),
    Venue(
      id: 'hongdae_rockbottom_1',
      name: 'Rock Bottom 홍대',
      description: '홍대의 대표적인 라이브 바&펍',
      imageUrl: '',
      location: const LatLng(37.5555, 126.9230),
      rating: 4.7,
      category: '나이트클럽',
      ticketUrl: 'https://example.com/ticket5',
      address: '서울특별시 마포구 홍대',
      phoneNumber: '02-5678-9012',
    ),
  ];
}

List<Venue> getItaewonVenues() {
  return [
    Venue(
      id: 'itaewon_livezone_1',
      name: 'LIVE Zone 이태원',
      description: '이태원의 유명한 호프/생맥주집, 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.5350, 126.9830),
      rating: 4.8,
      category: '호프/생맥주집',
      ticketUrl: 'https://example.com/ticket6',
      address: '서울특별시 용산구 이태원',
      phoneNumber: '02-6789-0123',
    ),
    Venue(
      id: 'itaewon_inn_1',
      name: 'The Inn Livehouse @ 이태원',
      description: '이태원에 위치한 인기 라이브 음악 바',
      imageUrl: '',
      location: const LatLng(37.5355, 126.9840),
      rating: 4.8,
      category: '라이브 음악 바',
      ticketUrl: 'https://example.com/ticket7',
      address: '서울특별시 용산구 이태원',
      phoneNumber: '02-7890-1234',
    ),
    Venue(
      id: 'itaewon_blujaz_1',
      name: 'Blu Jaz, 이태원점',
      description: '이태원의 펑키한 글로벌 바&그릴에서 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.5340, 126.9825),
      rating: 4.3,
      category: '술집',
      ticketUrl: 'https://example.com/ticket8',
      address: '서울특별시 용산구 이태원',
      phoneNumber: '02-8901-2345',
    ),
    Venue(
      id: 'itaewon_lenoir_1',
      name: 'Le Noir @ 이태원',
      description: '이태원의 분위기 좋은 칵테일 바에서 라이브 공연',
      imageUrl: '',
      location: const LatLng(37.5360, 126.9850),
      rating: 4.8,
      category: '칵테일바',
      ticketUrl: 'https://example.com/ticket9',
      address: '서울특별시 용산구 이태원',
      phoneNumber: '02-9012-3456',
    ),
    Venue(
      id: 'itaewon_bluefire_1',
      name: 'Bluefire Beach Club 이태원',
      description: '이태원의 인기 술집에서 라이브 음악과 해변 분위기',
      imageUrl: '',
      location: const LatLng(37.5330, 126.9815),
      rating: 4.7,
      category: '술집',
      ticketUrl: 'https://example.com/ticket10',
      address: '서울특별시 용산구 이태원',
      phoneNumber: '02-0123-4567',
    ),
  ];
}